pipeline {
    agent any

    environment {
        AWS_REGION = "ap-south-1"
        AWS_ACCOUNT_ID = "575126609591"
        BACKEND_REPO = "shipquick-backend"
        FRONTEND_REPO = "shipquick-frontend"
        IMAGE_TAG = "dev-${BUILD_NUMBER}"
        ECR_URL = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Backend Test') {
            steps {
                dir('shipquick-app/backend') {
                    sh 'npm install'
                    sh 'npm test'
                }
            }
        }

        stage('Build Docker Images') {
            steps {
                sh 'docker build -t $BACKEND_REPO:$IMAGE_TAG shipquick-app/backend'
                sh 'docker build -t $FRONTEND_REPO:$IMAGE_TAG shipquick-app/frontend'
            }
        }
	stage('Trivy Image Scan') {
    		steps {
        		sh 'trivy image --severity HIGH,CRITICAL $BACKEND_REPO:$IMAGE_TAG'
        		sh 'trivy image --severity HIGH,CRITICAL $FRONTEND_REPO:$IMAGE_TAG'
   		 }
	}

        stage('Login to ECR') {
            steps {
                sh 'aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URL'
            }
        }

        stage('Tag and Push Images') {
            steps {
                sh 'docker tag $BACKEND_REPO:$IMAGE_TAG $ECR_URL/$BACKEND_REPO:$IMAGE_TAG'
                sh 'docker tag $FRONTEND_REPO:$IMAGE_TAG $ECR_URL/$FRONTEND_REPO:$IMAGE_TAG'

                sh 'docker push $ECR_URL/$BACKEND_REPO:$IMAGE_TAG'
                sh 'docker push $ECR_URL/$FRONTEND_REPO:$IMAGE_TAG'
            }
        }
	stage('Update GitOps Repo') {
    steps {
        withCredentials([usernamePassword(
            credentialsId: 'github-creds',
            usernameVariable: 'GIT_USER',
            passwordVariable: 'GIT_TOKEN'
        )]) {
            sh '''
            rm -rf shipquick-gitops

            git clone https://${GIT_USER}:${GIT_TOKEN}@github.com/AravindS301/shipquick-gitops.git

            cd shipquick-gitops

            sed -i "s|image: .*shipquick-backend.*|image: ${ECR_URL}/${BACKEND_REPO}:${IMAGE_TAG}|" shipquick-gitops/k8s/backend-deployment.yaml

            sed -i "s|image: .*shipquick-frontend.*|image: ${ECR_URL}/${FRONTEND_REPO}:${IMAGE_TAG}|" shipquick-gitops/k8s/frontend-deployment.yaml

            git config user.email "jenkins@example.com"
            git config user.name "jenkins"

            git add .
            git commit -m "Update image tag to ${IMAGE_TAG}" || echo "No changes"

            git push
            '''
        }
    }
}
    }
}
