pipeline {
    agent any

    environment {
        AWS_REGION = "ap-south-1"
        AWS_ACCOUNT_ID = "575126609591"
        BACKEND_REPO = "shipquick-backend"
        FRONTEND_REPO = "shipquick-frontend"
        IMAGE_TAG = "dev-${BUILD_NUMBER}"
        ECR_URL = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Backend Test') {
            steps {
                dir('shipquick-app/ackend') {
                    sh 'npm install'
                    sh 'npm test'
                }
            }
        }

        stage('Build Docker Images') {
            steps {
                sh 'docker build -t $BACKEND_REPO:$IMAGE_TAG shipquick-app/backend'
                sh 'docker build -t $FRONTEND_REPO:$IMAGE_TAG shipquick-app/frontend'
            }
        }

        stage('Login to ECR') {
            steps {
                sh 'aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URL'
            }
        }

        stage('Tag and Push Images') {
            steps {
                sh 'docker tag $BACKEND_REPO:$IMAGE_TAG $ECR_URL/$BACKEND_REPO:$IMAGE_TAG'
                sh 'docker tag $FRONTEND_REPO:$IMAGE_TAG $ECR_URL/$FRONTEND_REPO:$IMAGE_TAG'

                sh 'docker push $ECR_URL/$BACKEND_REPO:$IMAGE_TAG'
                sh 'docker push $ECR_URL/$FRONTEND_REPO:$IMAGE_TAG'
            }
        }
    }
}
